"""Module 4 (part 1): Pydantic output schema for the clinical safety report.

Implements FR-4.1: exactly these five fields, validated on instantiation.
"""
from typing import List

from pydantic import BaseModel, Field

DEFAULT_DISCLAIMER = (
    'Student engineering project output — not real clinical guidance. '
    'This report was generated by an AI pipeline for skill demonstration only '
    'and must never be used for real medical decision-making.'
)


class ClinicalSafetyReport(BaseModel):
    """Strictly-structured output of the LLM report generator."""

    Eligible_For_Vaccine: bool = Field(
        ...,
        description='Whether the patient is eligible given risk and guidelines',
    )
    Recommended_Dose_mg: float = Field(
        ...,
        description='Recommended dose in mg, must respect retrieved guideline bounds',
    )
    Reasoning_Steps: List[str] = Field(
        ...,
        description='Ordered, human-readable reasoning steps behind the decision',
    )
    FDA_Safety_Warnings_Cited: List[str] = Field(
        ...,
        description='Exact guideline snippets the recommendation relies on',
    )
    Disclaimer: str = Field(
        default=DEFAULT_DISCLAIMER,
        description='Must always be present in the final report',
    )

    def to_markdown(self) -> str:
        """Human-readable rendering saved alongside the JSON (FR-4.6)."""
        lines = [
            '# Clinical Safety Report',
            '',
            f'**Eligible for vaccine:** {"Yes" if self.Eligible_For_Vaccine else "No"}',
            f'**Recommended dose:** {self.Recommended_Dose_mg:.1f} mg',
            '',
            '## Reasoning steps',
        ]
        lines += [f'{i}. {step}' for i, step in enumerate(self.Reasoning_Steps, 1)]
        lines += ['', '## FDA safety warnings cited']
        lines += [f'- {w}' for w in self.FDA_Safety_Warnings_Cited]
        lines += ['', f'> **Disclaimer:** {self.Disclaimer}', '']
        return '\n'.join(lines)
